Repository IVAO-XU/EG-Sector-File, pull requests merged in 2024-11, with the labels that each got.

#660 EGLL - Procedural Turns (SIDs)
  Include/egxx/egtt/sids/EGLL.sid
Labels: Enhancement

#659 2412 - Runway Characteristics Update
  Include/egxx/eg-nav/egxx-rwy.rwy
Labels: AIRAC

#658 2412 - EGNS Taxiway / Holding Points revised
  Include/egxx/egtt/airfield-layouts/EGNS.geo
  Include/egxx/egtt/taxiways/EGNS.txi
Labels: AIRAC

#657 2412 - EGSY Stands
  Include/egxx/egtt/gates/EGSY.gts
  Include/egxx/egtt/taxiways/EGSY.txi
Labels: Enhancement, AIRAC

#663 EGKK TXI/TXL
  Include/egxx/egtt/taxiways/EGKK.txi
Labels: First Timer Fix
