Repository IVAO-XU/EG-Sector-File, pull requests merged in 2024-03, with the labels that each got.

#479 2403 - EGKK Updates
  Include/egxx/egtt/airfield-layouts/EGKK.geo
  Include/egxx/egtt/airfield-layouts/EGKK.tfl
  Include/egxx/egtt/taxiways/EGKK.txi
Labels: Enhancement, AIRAC

#481 2403 EGNS Updates
  Include/egxx/eg-nav/ctr-cta-airport.airspace
  Include/egxx/egtt/airfield-layouts/EGNS.geo
  Include/egxx/egtt/airfield-layouts/EGNS.tfl
  Include/egxx/egtt/gates/EGNS.gts
  Include/egxx/egtt/taxiways/EGNS.txi
Labels: Bug, Enhancement, AIRAC

#489 2404 EGGD
  Include/egxx/egtt/airfield-layouts/EGGD.geo
  Include/egxx/egtt/airfield-layouts/EGGD.tfl
  Include/egxx/egtt/gates/EGGD.gts
  Include/egxx/egtt/taxiways/EGGD.txi
Labels: AIRAC

#490 EGEO Comms Fix
  Include/egxx/egpx/egpx-atc.atc
Labels: Bug

#496 EGPH Stand Amendment
  Include/egxx/egpx/gates/EGPH.gts
Labels: Bug
