Repository IVAO-XU/EG-Sector-File, pull requests merged in 2024-08, with the labels that each got.

#584 Borders CTA 3 Fix
  Include/egxx/eg-atc/egpx-ctr.plf
Labels: Bug

#594 egxx.isc fix (EGSY.geo added)
  egxx.isc
Labels: Bug

#592 Update EGPH.gts
  Include/egxx/egpx/gates/EGPH.gts
Labels: Bug

#573 2408 - EGNM Tug Release Points
  Include/egxx/egtt/airfield-layouts/EGNM.geo
  Include/egxx/egtt/gates/EGNM.gts
  Include/egxx/egtt/taxiways/EGNM.txi
Labels: AIRAC

#588 2408 - EGGD - New SMR (including 2408 changes)
  Include/egxx/egtt/airfield-layouts/EGGD.apr
  Include/egxx/egtt/airfield-layouts/EGGD.geo
  Include/egxx/egtt/airfield-layouts/EGGD.tfl
  Include/egxx/egtt/gates/EGGD.gts
  Include/egxx/egtt/taxiways/EGGD.txi
Labels: Enhancement, AIRAC

#601 EGCC Stand Layout Fix
  Include/egxx/egtt/airfield-layouts/EGCC.tfl
  Include/egxx/egtt/gates/EGCC.gts
Labels: Bug

#600 EGPF Stand Fix
  Include/egxx/egpx/gates/EGPF.gts
Labels: Enhancement

#597 EGSS - STAR Fix and Updates
  Include/egxx/egtt/stars/EGSS.str
Labels: Bug

#606 EGCC- STAR FIX - LIBSO1M
  Include/egxx/egtt/stars/EGCC.str
Labels: Bug, Enhancement

#605 EGGP Star Update
  Include/egxx/egtt/stars/EGGP.str
Labels: Bug, Enhancement

#610 EGKK Base of CAS fix
  Include/egxx/eg-nav/00DB.mva
Labels: Bug
