Repository IVAO-XU/EG-Sector-File, pull requests merged in 2024-04, with the labels that each got.

#517 EGGW Stand Fix
  Include/egxx/egtt/gates/EGGW.gts
Labels: Bug, Enhancement

#519 EGTK Creation
  Include/egxx/egtt/airfield-layouts/EGTK.geo
  Include/egxx/egtt/airfield-layouts/EGTK.tfl
  Include/egxx/egtt/gates/EGTK.gts
  Include/egxx/egtt/taxiways/EGTK.txi
  Include/egxx/egtt/visual/EGTK.vfi
Labels: Enhancement

#520 EGHA Creation
  Include/egxx/egtt/airfield-layouts/EGHA.tfl
  egxx.isc
Labels: Enhancement

#516 2405 EGCC
  Include/egxx/egtt/airfield-layouts/EGCC.geo
  Include/egxx/egtt/airfield-layouts/EGCC.tfl
  Include/egxx/egtt/gates/EGCC.gts
  Include/egxx/egtt/taxiways/EGCC.txi
Labels: AIRAC

#525 RMA Shaded Areas
  Include/egxx/eg-atc/shaded-rma.plf
  egxx.isc
Labels: Enhancement

#527 EGTT EGPX Shaded Area Recolour
  Include/egxx/eg-atc/egpx-ctr.plf
  Include/egxx/eg-atc/egpx-m-ctr.plf
  Include/egxx/eg-atc/egtt-c-ctr.plf
  Include/egxx/eg-atc/egtt-n-ctr.plf
  Include/egxx/eg-atc/egtt-s-ctr.plf
  Include/egxx/eg-atc/egtt-w-ctr.plf
Labels: Enhancement
