Repository IVAO-XU/EG-Sector-File, pull requests merged in 2024-05, with the labels that each got.

#532 EGWW SMR Full Re-Draw
  Include/egxx/egtt/airfield-layouts/EGGW.apr
  Include/egxx/egtt/airfield-layouts/EGGW.geo
  Include/egxx/egtt/airfield-layouts/EGGW.tfl
  Include/egxx/egtt/gates/EGGW.gts
  Include/egxx/egtt/taxiways/EGGW.txi
Labels: Enhancement

#534 EGLL Runway Calibration Fix
  Include/egxx/eg-nav/egxx-rwy.rwy
Labels: Bug, Enhancement

#538 EGTT-ATC file fix.
  Include/egxx/egtt/egtt-atc.atc
Labels: Enhancement, Help Required

#535 EGJJ VRP Fix
  Include/egxx/egtt/visual/EGJJ.vfi
Labels: Enhancement

#537 EGGP - POL4T SID Fix
  Include/egxx/eg-nav/egxx-procedure-fix.fix
Labels: Bug, Enhancement

#533 2406 EGSC Fix
  Include/egxx/eg-nav/egxx-rwy.rwy
Labels: Enhancement, AIRAC

#531 2406 EGTK Fix
  Include/egxx/egtt/airfield-layouts/EGTK.tfl
  Include/egxx/egtt/gates/EGTK.gts
Labels: Enhancement, AIRAC

#554 EGHH - .geo Coding Fix
  Include/egxx/egtt/airfield-layouts/EGHH.geo
Labels: Bug, Enhancement

#553 EGKK - Taxiway RA Restoration
  Include/egxx/egtt/airfield-layouts/EGKK.geo
  Include/egxx/egtt/airfield-layouts/EGKK.tfl
  Include/egxx/egtt/taxiways/EGKK.txi
Labels: Enhancement

#558 EGCB Barton SMR Fix
  Include/egxx/egtt/airfield-layouts/EGCB.tfl
Labels: Enhancement

#557 EGPK - Runway Markings Fix
  Include/egxx/egpx/airfield-layouts/EGPK.tfl
Labels: Bug, Enhancement
