Repository IVAO-XU/EG-Sector-File, pull requests merged in 2024-07, with the labels that each got.

#578 EGNX - EMW/EME Hold Fix
  Include/egxx/eg-nav/egxx-rwy.rwy
  Include/egxx/egtt/stars/EGNX.str
Labels: Enhancement

#577 EGNX - SID Procedural Turns
  Include/egxx/egtt/sids/EGNX.sid
Labels: Enhancement

#576 Procedure Fix Update
  Include/egxx/eg-nav/egxx-procedure-fix.fix
Labels: Enhancement

#579 2408 - JSY VOR Coordinate Update
  Include/egxx/eg-nav/egxx-vor.vor
Labels: AIRAC

#583 UN859 Fix
  Include/egxx/eg-nav/egxx-high-airways.hairway
Labels: Bug
