Repository IVAO-XU/EG-Sector-File, pull requests merged in 2024-12, with the labels that each got.

#668 Enroute MVA
  Include/egxx/eg-nav/00DB.mva
  Include/egxx/eg-nav/00IC.mva
  Include/egxx/eg-nav/egxx-apt.apt
  egxx.isc
Labels: Bug, Enhancement

#672 EGNX - New SMR 2413
  Include/egxx/egtt/airfield-layouts/EGNX.geo
  Include/egxx/egtt/airfield-layouts/EGNX.tfl
  Include/egxx/egtt/taxiways/EGNX.txi
Labels: Enhancement, AIRAC

#676 Further Updates Foreign Sectors
  Include/egxx/eg-atc/eg-foreign-atc.plf
Labels: Enhancement

#677 Foreign Sector Update 3
  Include/egxx/eg-atc/eg-foreign-atc.plf
Labels: Enhancement

#678 IC/DB Hot fix for 2413
  egxx.isc
Labels: Bug, AIRAC
