Repository IVAO-XU/EG-Sector-File, pull requests merged in 2025-09, with the labels that each got.

#847 Update EGDM.gts
  Include/egxx/eg-military/gates/EGDM.gts
Labels: Enhancement

#848 EGNX SID Fix
  Include/egxx/egtt/sids/EGNX.sid
Labels: Bug, Enhancement

#846 EGPF - Taxiway Labels
  Include/egxx/egpx/taxiways/EGPF.txi
Labels: Enhancement

#843 2509- EGHH Ground Layout
  Include/egxx/egtt/airfield-layouts/EGHH.tfl
  Include/egxx/egtt/gates/EGHH.gts
  Include/egxx/egtt/taxiways/EGHH.txi
Labels: AIRAC

#849 EGUB + EGXT New SMR
  Include/egxx/eg-military/airfield-layouts/EGUB.geo
  Include/egxx/eg-military/airfield-layouts/EGUB.plf
  Include/egxx/eg-military/airfield-layouts/EGXT.geo
  Include/egxx/eg-military/airfield-layouts/EGXT.plf
  Include/egxx/eg-military/gates/EGUB.gts
  Include/egxx/eg-military/gates/EGXT.gts
  Include/egxx/eg-military/taxiways/EGUB.txi
  Include/egxx/eg-military/taxiways/EGXT.txi
  egxx.isc
Labels: On Hold
