Repository IVAO-XU/EG-Sector-File, pull requests merged in 2025-06, with the labels that each got.

#727 Fixed Gatwick SMR Taxiway Label Error #726
  Include/egxx/egtt/taxiways/EGKK.txi
Labels: Enhancement

#740 2506 - EGBB Stand Updates
  Include/egxx/egtt/gates/EGBB.gts
Labels: Enhancement, AIRAC

#738 2506 CTA Updates
  Include/egxx/eg-nav/00DB.mva
  Include/egxx/eg-nav/egxx.artcc
Labels: AIRAC

#748 EGMC New SMR
  Include/egxx/egtt/airfield-layouts/EGMC.apr
  Include/egxx/egtt/airfield-layouts/EGMC.geo
  Include/egxx/egtt/airfield-layouts/EGMC.tfl
  Include/egxx/egtt/taxiways/EGMC.txi
Labels: Enhancement

#747 2502 - EGKK TDZ 08L/26R
  Include/egxx/egtt/airfield-layouts/EGKK.tfl
Labels: AIRAC

#745 2506 - EGGD West Apron new layout
  Include/egxx/egtt/airfield-layouts/EGGD.apr
  Include/egxx/egtt/airfield-layouts/EGGD.geo
  Include/egxx/egtt/airfield-layouts/EGGD.tfl
  Include/egxx/egtt/gates/EGGD.gts
Labels: Enhancement, AIRAC

#751 EGCC Manchester New SMR
  Include/egxx/egtt/airfield-layouts/EGCC.geo
  Include/egxx/egtt/airfield-layouts/EGCC.plf
  Include/egxx/egtt/airfield-layouts/EGCC.tfl
  Include/egxx/egtt/gates/EGCC.gts
  Include/egxx/egtt/taxiways/EGCC.txi
  egxx.isc
Labels: Enhancement, AIRAC

#754 2506 Hotfix
  Include/egxx/eg-military/stars/EGWU.str
  Include/egxx/egpx/stars/EGPK.str
  Include/egxx/egtt/stars/EGFF.str
  Include/egxx/egtt/stars/EGGD.str
  Include/egxx/egtt/stars/EGLL.str
Labels: Bug, AIRAC

#766 2506 Fix - EGPK Approach Transitions
  Include/egxx/eg-nav/egxx-fix.fix
  Include/egxx/eg-nav/egxx-procedure-fix.fix
  Include/egxx/egpx/stars/EGPK.str
Labels: Bug, Enhancement, AIRAC
